CREATE TABLE "fan_bands" (
	"fan_id" integer NOT NULL,
	"band_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fan_imports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fan_imports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" text NOT NULL,
	"filename" text NOT NULL,
	"band_id" integer,
	"row_count" integer NOT NULL,
	"added_count" integer NOT NULL,
	"imported_by_user_id" text,
	"created_at" text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" text NOT NULL,
	"email" text NOT NULL,
	"name" text,
	"country" text,
	"postal_code" text,
	"added_on" text NOT NULL,
	"extra" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"first_import_id" integer,
	"created_at" text DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
--> statement-breakpoint
ALTER TABLE "fan_bands" ADD CONSTRAINT "fan_bands_fan_id_fans_id_fk" FOREIGN KEY ("fan_id") REFERENCES "public"."fans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fan_bands" ADD CONSTRAINT "fan_bands_band_id_bands_id_fk" FOREIGN KEY ("band_id") REFERENCES "public"."bands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fan_imports" ADD CONSTRAINT "fan_imports_org_id_organization_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fan_imports" ADD CONSTRAINT "fan_imports_band_id_bands_id_fk" FOREIGN KEY ("band_id") REFERENCES "public"."bands"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fan_imports" ADD CONSTRAINT "fan_imports_imported_by_user_id_user_id_fk" FOREIGN KEY ("imported_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fans" ADD CONSTRAINT "fans_org_id_organization_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fans" ADD CONSTRAINT "fans_first_import_id_fan_imports_id_fk" FOREIGN KEY ("first_import_id") REFERENCES "public"."fan_imports"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "fan_bands_pk" ON "fan_bands" USING btree ("fan_id","band_id");--> statement-breakpoint
CREATE INDEX "fan_bands_band" ON "fan_bands" USING btree ("band_id");--> statement-breakpoint
CREATE INDEX "fan_imports_org" ON "fan_imports" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "fans_org" ON "fans" USING btree ("org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "fans_org_email" ON "fans" USING btree ("org_id","email");