// The Worker: the app itself (built by OpenNext), plus the hourly Bandcamp sync.
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so it's only there after a build:
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- @ts-expect-error would fail once it exists.
// @ts-ignore
import { default as handler } from "../.open-next/worker.js";

type Env = { CRON_SECRET?: string };

export default {
  fetch: handler.fetch,

  /** Cron trigger (wrangler.jsonc): ask the app to sync every account that's due, with up to 15 minutes to do it. */
  async scheduled(_event: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    if (!env.CRON_SECRET) {
      console.error("CRON_SECRET isn't set, so the hourly Bandcamp sync can't run.");
      return;
    }
    const request = new Request("https://cron.internal/api/cron/sync", { method: "POST", headers: { "x-cron-secret": env.CRON_SECRET } });
    const res: Response = await handler.fetch(request, env, ctx);
    console.log("Hourly Bandcamp sync:", res.status, await res.text());
  },
};
